/**
 * Error Codes for Hydraulic Network Web Application
 * 
 * This module defines standardized error codes for different error categories
 * including validation errors, calculation errors, network errors, and system errors.
 */

// Error code prefixes by category
export const ERROR_PREFIXES = {
  VALIDATION: 'VAL',
  CALCULATION: 'CALC',
  NETWORK: 'NET',
  SYSTEM: 'SYS',
  FILE: 'FILE',
  CONFIGURATION: 'CONFIG',
  AUTHENTICATION: 'AUTH',
  AUTHORIZATION: 'AUTHZ'
} as const;

// Validation error codes
export const VALIDATION_ERRORS = {
  // Required field errors
  REQUIRED_FIELD: `${ERROR_PREFIXES.VALIDATION}_001`,
  REQUIRED_IF: `${ERROR_PREFIXES.VALIDATION}_002`,
  REQUIRED_UNLESS: `${ERROR_PREFIXES.VALIDATION}_003`,
  
  // Type validation errors
  INVALID_TYPE: `${ERROR_PREFIXES.VALIDATION}_004`,
  INVALID_NUMBER: `${ERROR_PREFIXES.VALIDATION}_005`,
  INVALID_STRING: `${ERROR_PREFIXES.VALIDATION}_006`,
  INVALID_BOOLEAN: `${ERROR_PREFIXES.VALIDATION}_007`,
  INVALID_DATE: `${ERROR_PREFIXES.VALIDATION}_008`,
  INVALID_EMAIL: `${ERROR_PREFIXES.VALIDATION}_009`,
  INVALID_URL: `${ERROR_PREFIXES.VALIDATION}_010`,
  
  // Range validation errors
  MIN_VALUE: `${ERROR_PREFIXES.VALIDATION}_011`,
  MAX_VALUE: `${ERROR_PREFIXES.VALIDATION}_012`,
  MIN_LENGTH: `${ERROR_PREFIXES.VALIDATION}_013`,
  MAX_LENGTH: `${ERROR_PREFIXES.VALIDATION}_014`,
  MIN_ITEMS: `${ERROR_PREFIXES.VALIDATION}_015`,
  MAX_ITEMS: `${ERROR_PREFIXES.VALIDATION}_016`,
  
  // Pattern validation errors
  PATTERN_MISMATCH: `${ERROR_PREFIXES.VALIDATION}_017`,
  INVALID_FORMAT: `${ERROR_PREFIXES.VALIDATION}_018`,
  INVALID_CHARS: `${ERROR_PREFIXES.VALIDATION}_019`,
  
  // Hydraulic-specific validation errors
  INVALID_PHASE: `${ERROR_PREFIXES.VALIDATION}_020`,
  INVALID_PRESSURE: `${ERROR_PREFIXES.VALIDATION}_021`,
  INVALID_TEMPERATURE: `${ERROR_PREFIXES.VALIDATION}_022`,
  INVALID_FLOW_RATE: `${ERROR_PREFIXES.VALIDATION}_023`,
  INVALID_DIAMETER: `${ERROR_PREFIXES.VALIDATION}_024`,
  INVALID_VELOCITY: `${ERROR_PREFIXES.VALIDATION}_025`,
  INVALID_ROUGHNESS: `${ERROR_PREFIXES.VALIDATION}_026`,
  INVALID_LENGTH: `${ERROR_PREFIXES.VALIDATION}_027`,
  INVALID_ELEVATION: `${ERROR_PREFIXES.VALIDATION}_028`,
  INVALID_K_FACTOR: `${ERROR_PREFIXES.VALIDATION}_029`,
  INVALID_FR_PORT_DIAMETER: `${ERROR_PREFIXES.VALIDATION}_030`,
  INVALID_MOLECULAR_WEIGHT: `${ERROR_PREFIXES.VALIDATION}_031`,
  INVALID_VISCOSITY: `${ERROR_PREFIXES.VALIDATION}_032`,
  INVALID_DENSITY: `${ERROR_PREFIXES.VALIDATION}_033`,
  INVALID_Z_FACTOR: `${ERROR_PREFIXES.VALIDATION}_034`,
  INVALID_SPECIFIC_HEAT_RATIO: `${ERROR_PREFIXES.VALIDATION}_035`,
  
  // Cross-field validation errors
  INCONSISTENT_FIELDS: `${ERROR_PREFIXES.VALIDATION}_036`,
  DEPENDENCY_MISSING: `${ERROR_PREFIXES.VALIDATION}_037`,
  LOGIC_CONFLICT: `${ERROR_PREFIXES.VALIDATION}_038`,
  
  // Section validation errors
  SECTION_CONTINUITY: `${ERROR_PREFIXES.VALIDATION}_039`,
  DIAMETER_MISMATCH: `${ERROR_PREFIXES.VALIDATION}_040`,
  SECTION_ORDER: `${ERROR_PREFIXES.VALIDATION}_041`,
  INVALID_SECTION_ID: `${ERROR_PREFIXES.VALIDATION}_042`,
  
  // Fluid property validation errors
  FLUID_PROPERTY_CONSISTENCY: `${ERROR_PREFIXES.VALIDATION}_043`,
  PHASE_PROPERTY_MISMATCH: `${ERROR_PREFIXES.VALIDATION}_044`,
  PROPERTY_RANGE_EXCEEDED: `${ERROR_PREFIXES.VALIDATION}_045`
} as const;

// Calculation error codes
export const CALCULATION_ERRORS = {
  // Solver errors
  SOLVER_FAILED: `${ERROR_PREFIXES.CALCULATION}_001`,
  CONVERGENCE_FAILED: `${ERROR_PREFIXES.CALCULATION}_002`,
  ITERATION_LIMIT_EXCEEDED: `${ERROR_PREFIXES.CALCULATION}_003`,
  NUMERICAL_INSTABILITY: `${ERROR_PREFIXES.CALCULATION}_004`,
  DIVISION_BY_ZERO: `${ERROR_PREFIXES.CALCULATION}_005`,
  INVALID_SOLUTION: `${ERROR_PREFIXES.CALCULATION}_006`,
  
  // Hydraulic calculation errors
  INVALID_REYNOLDS_NUMBER: `${ERROR_PREFIXES.CALCULATION}_007`,
  INVALID_FRICTION_FACTOR: `${ERROR_PREFIXES.CALCULATION}_008`,
  INVALID_PRESSURE_DROP: `${ERROR_PREFIXES.CALCULATION}_009`,
  INVALID_VELOCITY_PROFILE: `${ERROR_PREFIXES.CALCULATION}_010`,
  INVALID_FLOW_REGIME: `${ERROR_PREFIXES.CALCULATION}_011`,
  
  // Physical constraint errors
  SUPERSONIC_FLOW: `${ERROR_PREFIXES.CALCULATION}_012`,
  CAVITATION_DETECTED: `${ERROR_PREFIXES.CALCULATION}_013`,
  EXCESSIVE_PRESSURE_DROP: `${ERROR_PREFIXES.CALCULATION}_014`,
  EXCESSIVE_VELOCITY: `${ERROR_PREFIXES.CALCULATION}_015`,
  NEGATIVE_PRESSURE: `${ERROR_PREFIXES.CALCULATION}_016`,
  
  // Boundary condition errors
  INVALID_BOUNDARY_CONDITIONS: `${ERROR_PREFIXES.CALCULATION}_017`,
  INCONSISTENT_BOUNDARIES: `${ERROR_PREFIXES.CALCULATION}_018`,
  UNPHYSICAL_BOUNDARIES: `${ERROR_PREFIXES.CALCULATION}_019`,
  
  // Network topology errors
  DISCONNECTED_NETWORK: `${ERROR_PREFIXES.CALCULATION}_020`,
  CIRCULAR_FLOW: `${ERROR_PREFIXES.CALCULATION}_021`,
  INVALID_TOPOLOGY: `${ERROR_PREFIXES.CALCULATION}_022`,
  
  // Gas flow calculation errors
  INVALID_COMPRESSIBILITY: `${ERROR_PREFIXES.CALCULATION}_023`,
  INVALID_GAS_LAW: `${ERROR_PREFIXES.CALCULATION}_024`,
  INVALID_ISOTHERMAL_ASSUMPTION: `${ERROR_PREFIXES.CALCULATION}_025`,
  INVALID_ADIABATIC_ASSUMPTION: `${ERROR_PREFIXES.CALCULATION}_026`
} as const;

// Network error codes
export const NETWORK_ERRORS = {
  // HTTP errors
  NETWORK_UNREACHABLE: `${ERROR_PREFIXES.NETWORK}_001`,
  CONNECTION_TIMEOUT: `${ERROR_PREFIXES.NETWORK}_002`,
  REQUEST_TIMEOUT: `${ERROR_PREFIXES.NETWORK}_003`,
  SERVER_ERROR: `${ERROR_PREFIXES.NETWORK}_004`,
  BAD_GATEWAY: `${ERROR_PREFIXES.NETWORK}_005`,
  SERVICE_UNAVAILABLE: `${ERROR_PREFIXES.NETWORK}_006`,
  GATEWAY_TIMEOUT: `${ERROR_PREFIXES.NETWORK}_007`,
  
  // API errors
  INVALID_ENDPOINT: `${ERROR_PREFIXES.NETWORK}_008`,
  METHOD_NOT_ALLOWED: `${ERROR_PREFIXES.NETWORK}_009`,
  RATE_LIMIT_EXCEEDED: `${ERROR_PREFIXES.NETWORK}_010`,
  API_VERSION_UNSUPPORTED: `${ERROR_PREFIXES.NETWORK}_011`,
  
  // WebSocket errors
  WEBSOCKET_CONNECTION_FAILED: `${ERROR_PREFIXES.NETWORK}_012`,
  WEBSOCKET_DISCONNECTED: `${ERROR_PREFIXES.NETWORK}_013`,
  WEBSOCKET_MESSAGE_ERROR: `${ERROR_PREFIXES.NETWORK}_014`,
  
  // Data format errors
  INVALID_JSON: `${ERROR_PREFIXES.NETWORK}_015`,
  INVALID_XML: `${ERROR_PREFIXES.NETWORK}_016`,
  INVALID_DATA_FORMAT: `${ERROR_PREFIXES.NETWORK}_017`,
  PARSE_ERROR: `${ERROR_PREFIXES.NETWORK}_018`
} as const;

// System error codes
export const SYSTEM_ERRORS = {
  // General system errors
  UNKNOWN_ERROR: `${ERROR_PREFIXES.SYSTEM}_001`,
  NOT_IMPLEMENTED: `${ERROR_PREFIXES.SYSTEM}_002`,
  DEPENDENCY_ERROR: `${ERROR_PREFIXES.SYSTEM}_003`,
  CONFIGURATION_ERROR: `${ERROR_PREFIXES.SYSTEM}_004`,
  INITIALIZATION_ERROR: `${ERROR_PREFIXES.SYSTEM}_005`,
  
  // Memory and resource errors
  OUT_OF_MEMORY: `${ERROR_PREFIXES.SYSTEM}_006`,
  RESOURCE_LIMIT_EXCEEDED: `${ERROR_PREFIXES.SYSTEM}_007`,
  STACK_OVERFLOW: `${ERROR_PREFIXES.SYSTEM}_008`,
  
  // Browser compatibility errors
  UNSUPPORTED_BROWSER: `${ERROR_PREFIXES.SYSTEM}_009`,
  FEATURE_NOT_SUPPORTED: `${ERROR_PREFIXES.SYSTEM}_010`,
  WEBGL_NOT_SUPPORTED: `${ERROR_PREFIXES.SYSTEM}_011`,
  
  // Performance errors
  PERFORMANCE_DEGRADATION: `${ERROR_PREFIXES.SYSTEM}_012`,
  TIMEOUT_ERROR: `${ERROR_PREFIXES.SYSTEM}_013`,
  DEADLOCK_DETECTED: `${ERROR_PREFIXES.SYSTEM}_014`
} as const;

// File error codes
export const FILE_ERRORS = {
  // Upload errors
  FILE_TOO_LARGE: `${ERROR_PREFIXES.FILE}_001`,
  INVALID_FILE_TYPE: `${ERROR_PREFIXES.FILE}_002`,
  FILE_CORRUPTED: `${ERROR_PREFIXES.FILE}_003`,
  FILE_TOO_MANY: `${ERROR_PREFIXES.FILE}_004`,
  UPLOAD_FAILED: `${ERROR_PREFIXES.FILE}_005`,
  
  // Parse errors
  YAML_PARSE_ERROR: `${ERROR_PREFIXES.FILE}_006`,
  JSON_PARSE_ERROR: `${ERROR_PREFIXES.FILE}_007`,
  XML_PARSE_ERROR: `${ERROR_PREFIXES.FILE}_008`,
  CSV_PARSE_ERROR: `${ERROR_PREFIXES.FILE}_009`,
  
  // Content validation errors
  INVALID_SCHEMA: `${ERROR_PREFIXES.FILE}_010`,
  MISSING_REQUIRED_FIELDS: `${ERROR_PREFIXES.FILE}_011`,
  INVALID_FIELD_VALUES: `${ERROR_PREFIXES.FILE}_012`,
  DUPLICATE_SECTION_IDS: `${ERROR_PREFIXES.FILE}_013`,
  INCONSISTENT_REFERENCES: `${ERROR_PREFIXES.FILE}_014`
} as const;

// Configuration error codes
export const CONFIGURATION_ERRORS = {
  // Configuration structure errors
  INVALID_CONFIG_STRUCTURE: `${ERROR_PREFIXES.CONFIGURATION}_001`,
  MISSING_REQUIRED_SECTION: `${ERROR_PREFIXES.CONFIGURATION}_002`,
  INVALID_SECTION_ORDER: `${ERROR_PREFIXES.CONFIGURATION}_003`,
  
  // Configuration value errors
  INVALID_CONFIG_VALUE: `${ERROR_PREFIXES.CONFIGURATION}_004`,
  OUT_OF_RANGE_VALUE: `${ERROR_PREFIXES.CONFIGURATION}_005`,
  DUPLICATE_CONFIG_KEY: `${ERROR_PREFIXES.CONFIGURATION}_006`,
  
  // Configuration compatibility errors
  VERSION_MISMATCH: `${ERROR_PREFIXES.CONFIGURATION}_007`,
  INCOMPATIBLE_CONFIG: `${ERROR_PREFIXES.CONFIGURATION}_008`,
  DEPRECATED_CONFIG: `${ERROR_PREFIXES.CONFIGURATION}_009`
} as const;

// Authentication error codes
export const AUTHENTICATION_ERRORS = {
  INVALID_CREDENTIALS: `${ERROR_PREFIXES.AUTHENTICATION}_001`,
  EXPIRED_TOKEN: `${ERROR_PREFIXES.AUTHENTICATION}_002`,
  INVALID_TOKEN: `${ERROR_PREFIXES.AUTHENTICATION}_003`,
  TOKEN_REQUIRED: `${ERROR_PREFIXES.AUTHENTICATION}_004`,
  ACCOUNT_LOCKED: `${ERROR_PREFIXES.AUTHENTICATION}_005`
} as const;

// Authorization error codes
export const AUTHORIZATION_ERRORS = {
  ACCESS_DENIED: `${ERROR_PREFIXES.AUTHORIZATION}_001`,
  INSUFFICIENT_PERMISSIONS: `${ERROR_PREFIXES.AUTHORIZATION}_002`,
  FORBIDDEN_ACTION: `${ERROR_PREFIXES.AUTHORIZATION}_003`,
  RESOURCE_NOT_FOUND: `${ERROR_PREFIXES.AUTHORIZATION}_004`
} as const;

// Error code to message mapping
export const ERROR_MESSAGES = {
  // Validation error messages
  [VALIDATION_ERRORS.REQUIRED_FIELD]: 'This field is required',
  [VALIDATION_ERRORS.REQUIRED_IF]: 'This field is required under certain conditions',
  [VALIDATION_ERRORS.REQUIRED_UNLESS]: 'This field is required unless certain conditions are met',
  [VALIDATION_ERRORS.INVALID_TYPE]: 'Invalid data type',
  [VALIDATION_ERRORS.INVALID_NUMBER]: 'Invalid number format',
  [VALIDATION_ERRORS.INVALID_STRING]: 'Invalid string format',
  [VALIDATION_ERRORS.INVALID_BOOLEAN]: 'Invalid boolean value',
  [VALIDATION_ERRORS.INVALID_DATE]: 'Invalid date format',
  [VALIDATION_ERRORS.INVALID_EMAIL]: 'Invalid email address format',
  [VALIDATION_ERRORS.INVALID_URL]: 'Invalid URL format',
  [VALIDATION_ERRORS.MIN_VALUE]: 'Value must be greater than or equal to {min}',
  [VALIDATION_ERRORS.MAX_VALUE]: 'Value must be less than or equal to {max}',
  [VALIDATION_ERRORS.MIN_LENGTH]: 'Text must be at least {min} characters long',
  [VALIDATION_ERRORS.MAX_LENGTH]: 'Text must not exceed {max} characters',
  [VALIDATION_ERRORS.MIN_ITEMS]: 'Array must contain at least {min} items',
  [VALIDATION_ERRORS.MAX_ITEMS]: 'Array must not contain more than {max} items',
  [VALIDATION_ERRORS.PATTERN_MISMATCH]: 'Value does not match required pattern',
  [VALIDATION_ERRORS.INVALID_FORMAT]: 'Invalid format',
  [VALIDATION_ERRORS.INVALID_CHARS]: 'Contains invalid characters',
  
  // Hydraulic-specific validation error messages
  [VALIDATION_ERRORS.INVALID_PHASE]: 'Invalid fluid phase. Must be liquid, gas, or vapor',
  [VALIDATION_ERRORS.INVALID_PRESSURE]: 'Invalid pressure value',
  [VALIDATION_ERRORS.INVALID_TEMPERATURE]: 'Invalid temperature value',
  [VALIDATION_ERRORS.INVALID_FLOW_RATE]: 'Invalid flow rate value',
  [VALIDATION_ERRORS.INVALID_DIAMETER]: 'Invalid pipe diameter',
  [VALIDATION_ERRORS.INVALID_VELOCITY]: 'Invalid flow velocity',
  [VALIDATION_ERRORS.INVALID_ROUGHNESS]: 'Invalid pipe roughness',
  [VALIDATION_ERRORS.INVALID_LENGTH]: 'Invalid pipe length',
  [VALIDATION_ERRORS.INVALID_ELEVATION]: 'Invalid elevation change',
  [VALIDATION_ERRORS.INVALID_K_FACTOR]: 'Invalid K-factor for fittings',
  [VALIDATION_ERRORS.INVALID_MOLECULAR_WEIGHT]: 'Invalid molecular weight',
  [VALIDATION_ERRORS.INVALID_VISCOSITY]: 'Invalid fluid viscosity',
  [VALIDATION_ERRORS.INVALID_DENSITY]: 'Invalid fluid density',
  [VALIDATION_ERRORS.INVALID_Z_FACTOR]: 'Invalid compressibility factor',
  [VALIDATION_ERRORS.INVALID_SPECIFIC_HEAT_RATIO]: 'Invalid specific heat ratio',
  
  // Calculation error messages
  [CALCULATION_ERRORS.SOLVER_FAILED]: 'Calculation solver failed to complete',
  [CALCULATION_ERRORS.CONVERGENCE_FAILED]: 'Numerical solution did not converge',
  [CALCULATION_ERRORS.ITERATION_LIMIT_EXCEEDED]: 'Maximum iteration limit exceeded',
  [CALCULATION_ERRORS.NUMERICAL_INSTABILITY]: 'Numerical instability detected',
  [CALCULATION_ERRORS.DIVISION_BY_ZERO]: 'Division by zero error',
  [CALCULATION_ERRORS.INVALID_SOLUTION]: 'Invalid solution generated',
  [CALCULATION_ERRORS.INVALID_REYNOLDS_NUMBER]: 'Invalid Reynolds number calculated',
  [CALCULATION_ERRORS.INVALID_FRICTION_FACTOR]: 'Invalid friction factor',
  [CALCULATION_ERRORS.INVALID_PRESSURE_DROP]: 'Invalid pressure drop calculation',
  [CALCULATION_ERRORS.INVALID_VELOCITY_PROFILE]: 'Invalid velocity profile',
  [CALCULATION_ERRORS.INVALID_FLOW_REGIME]: 'Invalid flow regime detected',
  [CALCULATION_ERRORS.SUPERSONIC_FLOW]: 'Supersonic flow conditions detected',
  [CALCULATION_ERRORS.CAVITATION_DETECTED]: 'Cavitation conditions detected',
  [CALCULATION_ERRORS.EXCESSIVE_PRESSURE_DROP]: 'Excessive pressure drop detected',
  [CALCULATION_ERRORS.EXCESSIVE_VELOCITY]: 'Excessive flow velocity detected',
  [CALCULATION_ERRORS.NEGATIVE_PRESSURE]: 'Negative pressure detected',
  
  // Network error messages
  [NETWORK_ERRORS.NETWORK_UNREACHABLE]: 'Network connection unavailable',
  [NETWORK_ERRORS.CONNECTION_TIMEOUT]: 'Connection timeout',
  [NETWORK_ERRORS.REQUEST_TIMEOUT]: 'Request timeout',
  [NETWORK_ERRORS.SERVER_ERROR]: 'Server error occurred',
  [NETWORK_ERRORS.BAD_GATEWAY]: 'Bad gateway error',
  [NETWORK_ERRORS.SERVICE_UNAVAILABLE]: 'Service temporarily unavailable',
  [NETWORK_ERRORS.GATEWAY_TIMEOUT]: 'Gateway timeout',
  [NETWORK_ERRORS.WEBSOCKET_CONNECTION_FAILED]: 'WebSocket connection failed',
  [NETWORK_ERRORS.WEBSOCKET_DISCONNECTED]: 'WebSocket connection lost',
  
  // File error messages
  [FILE_ERRORS.FILE_TOO_LARGE]: 'File size exceeds maximum limit of {maxSize}',
  [FILE_ERRORS.INVALID_FILE_TYPE]: 'Invalid file type. Supported formats: {formats}',
  [FILE_ERRORS.YAML_PARSE_ERROR]: 'YAML parse error at line {line}, column {column}',
  [FILE_ERRORS.JSON_PARSE_ERROR]: 'JSON parse error at position {position}',
  [FILE_ERRORS.INVALID_SCHEMA]: 'Configuration does not match required schema',
  
  // System error messages
  [SYSTEM_ERRORS.UNKNOWN_ERROR]: 'An unknown error occurred',
  [SYSTEM_ERRORS.NOT_IMPLEMENTED]: 'Feature not yet implemented',
  [SYSTEM_ERRORS.TIMEOUT_ERROR]: 'Operation timed out',
  
  // Configuration error messages
  [CONFIGURATION_ERRORS.INVALID_CONFIG_STRUCTURE]: 'Invalid configuration structure',
  [CONFIGURATION_ERRORS.MISSING_REQUIRED_SECTION]: 'Required configuration section missing',
  [CONFIGURATION_ERRORS.VERSION_MISMATCH]: 'Configuration version mismatch'
} as const;

// Error severity mapping
export const ERROR_SEVERITY_MAPPING = {
  [VALIDATION_ERRORS.REQUIRED_FIELD]: 'error' as const,
  [VALIDATION_ERRORS.INVALID_TYPE]: 'error' as const,
  [VALIDATION_ERRORS.MIN_VALUE]: 'warning' as const,
  [VALIDATION_ERRORS.MAX_VALUE]: 'warning' as const,
  [VALIDATION_ERRORS.INVALID_PHASE]: 'error' as const,
  [VALIDATION_ERRORS.INVALID_PRESSURE]: 'error' as const,
  [VALIDATION_ERRORS.INVALID_VELOCITY]: 'warning' as const,
  [CALCULATION_ERRORS.SOLVER_FAILED]: 'critical' as const,
  [CALCULATION_ERRORS.CONVERGENCE_FAILED]: 'error' as const,
  [CALCULATION_ERRORS.NUMERICAL_INSTABILITY]: 'critical' as const,
  [CALCULATION_ERRORS.SUPERSONIC_FLOW]: 'warning' as const,
  [CALCULATION_ERRORS.CAVITATION_DETECTED]: 'warning' as const,
  [NETWORK_ERRORS.NETWORK_UNREACHABLE]: 'error' as const,
  [NETWORK_ERRORS.CONNECTION_TIMEOUT]: 'error' as const,
  [SYSTEM_ERRORS.UNKNOWN_ERROR]: 'critical' as const,
  [SYSTEM_ERRORS.NOT_IMPLEMENTED]: 'info' as const,
  [FILE_ERRORS.FILE_TOO_LARGE]: 'error' as const,
  [FILE_ERRORS.INVALID_FILE_TYPE]: 'warning' as const,
  [CONFIGURATION_ERRORS.INVALID_CONFIG_STRUCTURE]: 'error' as const
} as const;